### ISSUE TITLE
Could you provide the ferplus_trainvalid_list.txt

### ISSUE THREAD

**Issue by zzzzzzyang** [1980x/CCT#3]
For a fair comparsion, could you provide the ferplus_trainvalid_list.txt and ferplus_test.txt? Thanks a lot.

**Comment by 1980x** [comment]
[trainvalid.csv](https://github.com/1980x/CCT/files/7876718/trainvalid.csv)
[test.csv](https://github.com/1980x/CCT/files/7876719/test.csv)

**Comment by 1980x** [comment]
train valid is train + valid

**Comment by zzzzzzyang** [comment]
thanks，I already have these two csv files,  I just want to know which mode do you choose to generate one-hot label? majority?

**Comment by 1980x** [comment]
Yes
